// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tihzvdrwejnzeiaectey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpaHp2ZHJ3ZWpuemVpYWVjdGV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3NDQzNjUsImV4cCI6MjA1MTMyMDM2NX0.XqKClaTabqTtzZ-J4rBR-f2zTsQ64FxAKR0mdyKvsHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);